server:
  port: 9999

#thymeleaf start
spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  #thymeleaf end
  messages:
    basename: i18n.login

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.26.88.216:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456

  redis:
    host: 120.26.88.216
    port: 6382
    password:
    timeout: 10000
#    maxIdle: 300
#    maxTotal: 1000
#    maxWaitMillis: 1000
#    minEvictableIdleTimeMillis: 300000
#    numTestsPerEvictionRun: 1024
#    timeBetweenEvictionRunsMillis: 30000
#    testOnBorrow: true
#    testWhileIdle: true
